"""End-to-end proof of Phase 10's exit criteria: every listed document
source type (PDF/DOCX/TXT/CSV/Markdown/URL/YouTube) uploads/imports,
processes to `indexed` status via the real document-processing task logic,
and appears searchable afterward via `GET /knowledge-base/search` (Phase 9).
No mocks: real Postgres+pgvector, real MinIO object storage, the real
BGE-large embedding model (1024-dim, matching the fixed `embeddings` column
— see docs/architecture.md § 7).

Opt-in like the other integration tests (RUN_INTEGRATION_TESTS=1 +
DATABASE_URL), additionally skipped if MinIO isn't reachable at
MINIO_ENDPOINT (default localhost:9000) — same "skip if the live dependency
isn't there" posture as the Ollama-gated pipeline test.

`celery_app.send_task` is stubbed for each upload/import call for the same
reason as test_research_pipeline.py: no broker in this sandbox. The document
processing task's async body (app/workers/tasks.py::_process_document_async)
is invoked directly afterward instead. YouTube transcript fetches are
tolerated as a soft failure (network/rate-limit dependent, same posture as
ai/tests/test_loaders.py's live YouTube test) — every *other* source type
must succeed for this test to pass.
"""

import io
import os
import uuid
from collections.abc import AsyncIterator, Iterator
from unittest.mock import patch

import docx
import httpx
import pytest
from fastapi.testclient import TestClient

import app.workers.tasks as tasks_module
from app.core.config import Settings
from app.core.container import Container
from app.core.db import create_engine as create_db_engine
from app.core.db import create_session_factory
from app.core.oauth import build_oauth_registry
from app.main import app as fastapi_app

MINIO_ENDPOINT = os.environ.get("MINIO_ENDPOINT", "localhost:9000")


def _minio_reachable() -> bool:
    try:
        response = httpx.get(f"http://{MINIO_ENDPOINT}/minio/health/live", timeout=2.0)
        return response.status_code == 200
    except httpx.HTTPError:
        return False


pytestmark = [
    pytest.mark.asyncio,
    pytest.mark.skipif(
        os.environ.get("RUN_INTEGRATION_TESTS") != "1",
        reason="opt-in: set RUN_INTEGRATION_TESTS=1 and DATABASE_URL to a disposable pg db",
    ),
    pytest.mark.skipif(not _minio_reachable(), reason=f"no MinIO reachable at {MINIO_ENDPOINT}"),
]


@pytest.fixture(autouse=True)
async def _wire_worker_container() -> AsyncIterator[None]:
    # Document processing never touches container.llm, so no Ollama wiring
    # needed here (contrast test_research_pipeline.py's fixture). Redis is
    # unused by this path too — reuse the API's own real client rather than
    # standing up a fake one just to satisfy Container's constructor. MinIO
    # bucket name is copied from the *real* API container (built separately,
    # at app import time) rather than set independently — uploads go through
    # that container, downloads through this one, and both must agree on
    # which bucket holds the bytes.
    api_settings = fastapi_app.state.container.settings
    settings = Settings(
        database_url=os.environ["DATABASE_URL"],
        embedding_provider="bge",
        bge_model_name="BAAI/bge-large-en-v1.5",
        embedding_dimension=1024,
        minio_endpoint=MINIO_ENDPOINT,
        minio_bucket_documents=api_settings.minio_bucket_documents,
    )
    engine = create_db_engine(settings.database_url)
    tasks_module._container = Container(
        settings=settings,
        db_engine=engine,
        db_sessionmaker=create_session_factory(engine),
        oauth=build_oauth_registry(settings),
        redis=fastapi_app.state.container.redis,
    )
    yield
    tasks_module._container = None
    await engine.dispose()


@pytest.fixture
def client() -> Iterator[TestClient]:
    with TestClient(fastapi_app) as c:
        yield c


def _unique_email() -> str:
    return f"{uuid.uuid4().hex}@example.com"


def _build_minimal_pdf(text: str) -> bytes:
    """See ai/tests/test_loaders.py's identical helper for why this is
    hand-built rather than generated by a library — pypdf has no
    page-writing API of its own."""
    objects = [
        b"<</Type/Catalog/Pages 2 0 R>>",
        b"<</Type/Pages/Kids[3 0 R]/Count 1>>",
        b"<</Type/Page/Parent 2 0 R/Resources<</Font<</F1 4 0 R>>>>"
        b"/MediaBox[0 0 200 200]/Contents 5 0 R>>",
        b"<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>",
    ]
    stream = f"BT /F1 24 Tf 10 100 Td ({text}) Tj ET".encode()
    objects.append(
        b"<</Length " + str(len(stream)).encode() + b">>\nstream\n" + stream + b"\nendstream"
    )

    out = io.BytesIO()
    out.write(b"%PDF-1.4\n")
    offsets = []
    for index, body in enumerate(objects, start=1):
        offsets.append(out.tell())
        out.write(str(index).encode() + b" 0 obj" + body + b"endobj\n")
    xref_offset = out.tell()
    count = len(objects) + 1
    out.write(b"xref\n")
    out.write(f"0 {count}\n".encode())
    out.write(b"0000000000 65535 f \n")
    for offset in offsets:
        out.write(f"{offset:010d} 00000 n \n".encode())
    out.write(b"trailer\n")
    out.write(f"<</Size {count}/Root 1 0 R>>\n".encode())
    out.write(b"startxref\n" + str(xref_offset).encode() + b"\n%%EOF")
    return out.getvalue()


async def _process(document_id: str) -> None:
    await tasks_module._process_document_async(uuid.UUID(document_id))


async def test_every_source_type_uploads_or_imports_and_becomes_searchable(
    client: TestClient,
) -> None:
    email, password = _unique_email(), "correct-horse-battery-staple"
    resp = client.post(
        "/api/v1/auth/register",
        json={"email": email, "password": password, "full_name": "Docs Tester"},
    )
    assert resp.status_code == 201, resp.text
    resp = client.post("/api/v1/auth/login", json={"email": email, "password": password})
    assert resp.status_code == 200, resp.text
    headers = {"Authorization": f"Bearer {resp.json()['access_token']}"}

    resp = client.post("/api/v1/projects", json={"name": "Docs Test Project"}, headers=headers)
    assert resp.status_code == 201, resp.text
    project_id = resp.json()["id"]

    docx_buffer = io.BytesIO()
    docx_document = docx.Document()
    docx_document.add_paragraph(
        "Photosynthesis converts sunlight into chemical energy stored in plants."
    )
    docx_document.save(docx_buffer)

    uploads = [
        (
            "report.pdf",
            _build_minimal_pdf("The mitochondria is the powerhouse of the cell"),
            "application/pdf",
        ),
        (
            "notes.docx",
            docx_buffer.getvalue(),
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ),
        (
            "plain.txt",
            b"The Great Wall of China stretches across northern China for thousands of miles.",
            "text/plain",
        ),
        ("data.csv", b"planet,distance_au\nMercury,0.39\nVenus,0.72\n", "text/csv"),
        (
            "readme.md",
            b"# Volcanoes\n\nVolcanoes form where magma reaches the Earth's surface.",
            "text/markdown",
        ),
    ]

    document_ids: dict[str, str] = {}
    for filename, content, content_type in uploads:
        with patch("app.api.v1.documents.celery_app.send_task") as send_task:
            resp = client.post(
                "/api/v1/documents/upload",
                data={"project_id": project_id},
                files={"file": (filename, content, content_type)},
                headers=headers,
            )
        assert resp.status_code == 201, resp.text
        body = resp.json()
        assert body["status"] == "pending"
        send_task.assert_called_once_with("knowledge_base.process_document", args=[body["id"]])
        await _process(body["id"])
        document_ids[filename] = body["id"]

    url_source = "https://example.com"
    youtube_source = "https://www.youtube.com/watch?v=jNQXAC9IdLA"
    for url, expected_source_type in ((url_source, "url"), (youtube_source, "youtube")):
        with patch("app.api.v1.documents.celery_app.send_task"):
            resp = client.post(
                "/api/v1/documents/import-url",
                json={"project_id": project_id, "url": url},
                headers=headers,
            )
        assert resp.status_code == 201, resp.text
        body = resp.json()
        assert body["source_type"] == expected_source_type
        document_ids[url] = body["id"]

    await _process(document_ids[url_source])
    try:
        await _process(document_ids[youtube_source])
        youtube_processed = True
    except Exception:  # noqa: BLE001 - YouTube transcript fetch is a live, rate-limit-prone dependency
        youtube_processed = False

    reliable_documents = {k: v for k, v in document_ids.items() if k != youtube_source}
    for name, document_id in reliable_documents.items():
        resp = client.get(f"/api/v1/documents/{document_id}", headers=headers)
        assert resp.status_code == 200, resp.text
        assert resp.json()["status"] == "indexed", f"{name} did not index: {resp.json()}"

    if youtube_processed:
        resp = client.get(f"/api/v1/documents/{document_ids[youtube_source]}", headers=headers)
        assert resp.json()["status"] == "indexed"

    resp = client.get(
        "/api/v1/knowledge-base/search",
        params={"project_id": project_id, "q": "powerhouse of the cell", "top_k": 5},
        headers=headers,
    )
    assert resp.status_code == 200, resp.text
    results = resp.json()
    assert any("mitochondria" in r["chunk_text"].lower() for r in results)

    resp = client.get(f"/api/v1/projects/{project_id}/documents", headers=headers)
    assert resp.status_code == 200, resp.text
    listed = resp.json()
    assert len(listed) == len(document_ids)
    for entry in listed:
        if entry["status"] == "indexed":
            assert entry["chunk_count"] >= 1

    pdf_document_id = document_ids["report.pdf"]
    resp = client.delete(f"/api/v1/documents/{pdf_document_id}", headers=headers)
    assert resp.status_code == 204
    resp = client.get(f"/api/v1/documents/{pdf_document_id}", headers=headers)
    assert resp.status_code == 404


async def test_upload_rejects_an_unsupported_file_extension(client: TestClient) -> None:
    email, password = _unique_email(), "correct-horse-battery-staple"
    client.post(
        "/api/v1/auth/register",
        json={"email": email, "password": password, "full_name": "Docs Tester"},
    )
    resp = client.post("/api/v1/auth/login", json={"email": email, "password": password})
    headers = {"Authorization": f"Bearer {resp.json()['access_token']}"}

    resp = client.post("/api/v1/projects", json={"name": "Rejects Project"}, headers=headers)
    project_id = resp.json()["id"]

    resp = client.post(
        "/api/v1/documents/upload",
        data={"project_id": project_id},
        files={"file": ("archive.zip", b"PK\x03\x04", "application/zip")},
        headers=headers,
    )
    assert resp.status_code == 422


async def test_upload_rejects_a_project_that_is_not_the_caller_s(client: TestClient) -> None:
    email, password = _unique_email(), "correct-horse-battery-staple"
    client.post(
        "/api/v1/auth/register",
        json={"email": email, "password": password, "full_name": "Docs Tester"},
    )
    resp = client.post("/api/v1/auth/login", json={"email": email, "password": password})
    headers = {"Authorization": f"Bearer {resp.json()['access_token']}"}

    other_email, other_password = _unique_email(), "correct-horse-battery-staple"
    client.post(
        "/api/v1/auth/register",
        json={"email": other_email, "password": other_password, "full_name": "Other"},
    )
    resp = client.post(
        "/api/v1/auth/login", json={"email": other_email, "password": other_password}
    )
    other_headers = {"Authorization": f"Bearer {resp.json()['access_token']}"}

    resp = client.post(
        "/api/v1/projects", json={"name": "Not Yours"}, headers=other_headers
    )
    other_project_id = resp.json()["id"]

    resp = client.post(
        "/api/v1/documents/upload",
        data={"project_id": other_project_id},
        files={"file": ("notes.txt", b"hello", "text/plain")},
        headers=headers,
    )
    assert resp.status_code == 404
